version: '3'
services:
######################################
# Applications Container
######################################
  app:
    container_name: app-flask
    build:
      context: ./app
    # command: gunicorn -b 0.0.0.0:5000 app.wsgi:app --reload
    environment:
      PORT: 5000
    links: 
      - mongodb
      - redis
    volumes:
      - ./app:/app
    ports:
      - 8000:5000
######################################
# MongoDB Container
######################################
  mongodb:
    container_name: mongodb
    build:
      context: mongo
    volumes:
      - ./mongo/data:/data
      - ./mongo/init.json:/init.json
    ports:
      - 7017:27017
######################################
# Redis Container
######################################
  redis:
    container_name: redis
    image: redis:4.0.1-alpine
    volumes:
      - ./redis/data:/data
    ports:
      - 6379:6379
    links:
      - mongodb
