version: '3'
services:
######################################
# Applications Container
######################################
  app:
    container_name: app-flask
    build: 
      context: ./app
    command: gunicorn -b 0.0.0.0:5000 app.main:app --reload
    links: 
      - mongodb
    volumes:
      - ./app:/app
    ports:
      - 5000:5000
######################################
# MongoDB Container
######################################
  mongodb:
    container_name: mongodb
    build: 
      context: mongo
    volumes:
      - ./mongo/data:/data
    ports:
      - 27017:27017